
### Build Trin Execution From Git:
## Pulls trin execution from a git repository and builds it from source.

## Builder stage: Compiles trin execution from a git repository
FROM rust:latest as builder

ARG github=ethereum/trin
ARG tag=master

RUN apt-get update && apt-get install -y libclang-dev pkg-config build-essential \
    && echo "Cloning: $github - $tag" \
    && git clone --depth 1 --branch $tag https://github.com/$github trin-execution \
    && cd trin-execution && cargo build --release \
    && cp target/release/trin-execution /usr/local/bin/trin-execution

## Final stage: Sets up the environment for running trin execution
FROM debian:latest
RUN apt-get update && apt-get install -y bash curl jq \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Copy compiled binary from builder
COPY --from=builder /usr/local/bin/trin-execution /usr/local/bin/trin-execution

# Add genesis mapper script, startup script, and enode URL retriever script
COPY genesis.json /genesis.json
COPY mapper.jq /mapper.jq
COPY trin-execution.sh /trin-execution.sh
COPY enode.sh /hive-bin/enode.sh

# Set execute permissions for scripts
RUN chmod +x /trin-execution.sh /hive-bin/enode.sh

# Create version.txt
RUN /usr/local/bin/trin-execution --version | head -1 > /version.txt

# Export the usual networking ports
EXPOSE 8545 8546 30303 30303/udp 9009/udp

ENTRYPOINT ["/trin-execution.sh"]