### Build Trin Execution Locally:
## Requires a copy of <trin-execution>/ -> hive/clients/trin-execution/<trin-execution>

## Builder stage: Compiles trin execution from a git repository
FROM rust:latest as builder

# Default local client path: clients/trin-execution/<trin-execution>
ARG local_path=trin-execution
COPY $local_path trin-execution

RUN apt-get update && apt-get install -y libclang-dev pkg-config build-essential \
    && cd trin-execution && cargo build --release \
    && cp target/release/trin-execution /usr/local/bin/trin-execution

## Final stage: Sets up the environment for running trin execution
FROM debian:latest
RUN apt-get update && apt-get install -y bash curl jq \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Copy compiled binary from builder
COPY --from=builder /usr/local/bin/trin-execution /usr/local/bin/trin-execution

# Add genesis mapper script, startup script, and enode URL retriever script
COPY genesis.json /genesis.json
COPY mapper.jq /mapper.jq
COPY trin-execution.sh /trin-execution.sh
COPY enode.sh /hive-bin/enode.sh

# Set execute permissions for scripts
RUN chmod +x /trin-execution.sh /hive-bin/enode.sh

# Create version.txt
RUN /usr/local/bin/trin-execution --version | head -1 > /version.txt

# Export the usual networking ports
EXPOSE 8545 8546 30303 30303/udp 9009/udp

ENTRYPOINT ["/trin-execution.sh"]